<a href="https://colab.research.google.com/github/sanjeevchikkam/Medicinemapping/blob/main/MedicineMapping(Fuzzy%20matching).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Start the project

## Install and import libraries

In [ ]:
!pip install rapidfuzz
import pandas as pd
import re
from rapidfuzz import process, fuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 84.1 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3

### upload the pharmacy and master medicine id and name

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pharmacy_medicine.csv to pharmacy_medicine.csv
Saving master_medicine.csv to master_medicine.csv

In [ ]:
pharmacy = pd.read_csv("pharmacy_medicine.csv")
master = pd.read_csv("master_medicine.csv")

In [ ]:
pharmacy["medicine_name"]

0            Paracetamol 500mg Tab
1         Paracetamol 650mg Tablet
2            Amoxycillin 250mg Cap
3       Amoxycillin 500 mg Capsule
4              Ibuprofen 200mg Tab
5           Ibuprofen 400mg Tablet
6               Cetrizine 10mg Tab
7        Levocetrizine 5 mg Tablet
8              Metformin 500mg Tab
9              Metformin 1g Tablet
10               Amlodipin 5mg Tab
11          Amlodipine 10mg Tablet
12           Atorvastatin 10mg Tab
13              Atorva 20mg Tablet
14          Azithromycin 250mg Tab
15            Azithro 500mg Tablet
16               Losartan 50mg Tab
17    Losartan Potassium 100mg Tab
18              Omeprazol 20mg Cap
19         Omeprazole 40mg Capsule
20           Pantoprazole 40mg Tab
21          Rabeprazol 20mg Tablet
22            Montelukast 10mg Tab
23          Montelukast 5mg Tablet
24                    Dolo 650 Tab
25                Crocin 500mg Tab
26          Diclofenac 50mg Tablet
27       Diclofenac Injection 75mg
28            Insulin Glargine Inj
29       Regular Insulin Injection
30           Salbutamol Inhalation
31           Budesonide Inhalation
32            Clopidogrel 75mg Tab
33             Aspirin 75mg Tablet
34               Aspirin 150mg Tab
35         Telmisartan 40mg Tablet
36            Telmisartan 80mg Tab
37           Gliclazid 30mg Tablet
38             Gliclazide 60mg Tab
39          Glimepiride 1mg Tablet
40             Glimepiride 2mg Tab
41          Glimepiride 4mg Tablet
42             Furosemide 40mg Tab
43      Spironolactone 25mg Tablet
44    Hydrochlorothiazide 25mg Tab
45     Vitamin D3 60000 IU Capsule
46              Folic Acid 5mg Tab
47     Calcium Carbonate 500mg Tab
48               Vit B Complex Cap
49                      IFA Tablet
Name: medicine_name, dtype: object

# Write the Normalize text

In [ ]:
def normalize_text(text):

    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [ ]:
pharmacy["normalized_name"] = pharmacy["medicine_name"].apply(normalize_text)
master["normalized_name"] = master["medicine_name"].apply(normalize_text)

In [ ]:
master["normalized_name"]

0            paracetamol 500 mg tablet
1            paracetamol 650 mg tablet
2           amoxicillin 250 mg capsule
3           amoxicillin 500 mg capsule
4              ibuprofen 200 mg tablet
5              ibuprofen 400 mg tablet
6              cetirizine 10 mg tablet
7           levocetirizine 5 mg tablet
8              metformin 500 mg tablet
9             metformin 1000 mg tablet
10              amlodipine 5 mg tablet
11             amlodipine 10 mg tablet
12           atorvastatin 10 mg tablet
13           atorvastatin 20 mg tablet
14          azithromycin 250 mg tablet
15          azithromycin 500 mg tablet
16               losartan 50 mg tablet
17              losartan 100 mg tablet
18            omeprazole 20 mg capsule
19            omeprazole 40 mg capsule
20           pantoprazole 40 mg tablet
21            rabeprazole 20 mg tablet
22            montelukast 10 mg tablet
23             montelukast 5 mg tablet
24                  dolo 650 mg tablet
25                crocin 500 mg tablet
26             diclofenac 50 mg tablet
27          diclofenac 75 mg injection
28          insulin glargine injection
29           insulin regular injection
30                  salbutamol inhaler
31                  budesonide inhaler
32            clopidogrel 75 mg tablet
33                aspirin 75 mg tablet
34               aspirin 150 mg tablet
35            telmisartan 40 mg tablet
36            telmisartan 80 mg tablet
37             gliclazide 30 mg tablet
38             gliclazide 60 mg tablet
39             glimepiride 1 mg tablet
40             glimepiride 2 mg tablet
41             glimepiride 4 mg tablet
42             furosemide 40 mg tablet
43         spironolactone 25 mg tablet
44    hydrochlorothiazide 25 mg tablet
45    cholecalciferol 60000 iu capsule
46              folic acid 5 mg tablet
47     calcium carbonate 500 mg tablet
48           vitamin b complex capsule
49              iron folic acid tablet
Name: normalized_name, dtype: object

In [ ]:
pharmacy["normalized_name"]

0            paracetamol 500mg tablet
1         paracetamol 650mg tabletlet
2           amoxycillin 250mg capsule
3      amoxycillin 500 mg capsulesule
4              ibuprofen 200mg tablet
5           ibuprofen 400mg tabletlet
6               cetrizine 10mg tablet
7        levocetrizine 5 mg tabletlet
8              metformin 500mg tablet
9              metformin 1g tabletlet
10               amlodipin 5mg tablet
11          amlodipine 10mg tabletlet
12           atorvastatin 10mg tablet
13              atorva 20mg tabletlet
14          azithromycin 250mg tablet
15            azithro 500mg tabletlet
16               losartan 50mg tablet
17    losartan potassium 100mg tablet
18             omeprazol 20mg capsule
19        omeprazole 40mg capsulesule
20           pantoprazole 40mg tablet
21          rabeprazol 20mg tabletlet
22            montelukast 10mg tablet
23          montelukast 5mg tabletlet
24                    dolo 650 tablet
25                crocin 500mg tablet
26          diclofenac 50mg tabletlet
27    diclofenac injectionection 75mg
28         insulin glargine injection
29    regular insulin injectionection
30              salbutamol inhalation
31              budesonide inhalation
32            clopidogrel 75mg tablet
33             aspirin 75mg tabletlet
34               aspirin 150mg tablet
35         telmisartan 40mg tabletlet
36            telmisartan 80mg tablet
37           gliclazid 30mg tabletlet
38             gliclazide 60mg tablet
39          glimepiride 1mg tabletlet
40             glimepiride 2mg tablet
41          glimepiride 4mg tabletlet
42             furosemide 40mg tablet
43      spironolactone 25mg tabletlet
44    hydrochlorothiazide 25mg tablet
45    vitamin d3 60000 iu capsulesule
46              folic acid 5mg tablet
47     calcium carbonate 500mg tablet
48              vit b complex capsule
49                      ifa tabletlet
Name: normalized_name, dtype: object

### replace tab -> tablet

In [ ]:
abbrev = {
    r"\btab\b": "tablet",
    r"\bcap\b": "capsule",
    r"\binj\b": "injection",
    r"\bsyp\b": "syrup"
}

pharmacy["normalized_name"] = pharmacy["normalized_name"].replace(abbrev, regex=True)

In [ ]:
abbrev = {
    "tab": "tablet",
    "cap": "capsule",
    "inj": "injection",
    "syp": "syrup"
}

for k, v in abbrev.items():
    pharmacy["normalized_name"] = pharmacy["normalized_name"].str.replace(
        rf"\b{k}\b", v, regex=True
    )

In [ ]:
pharmacy["normalized_name"]

0            paracetamol 500mg tablet
1         paracetamol 650mg tabletlet
2           amoxycillin 250mg capsule
3      amoxycillin 500 mg capsulesule
4              ibuprofen 200mg tablet
5           ibuprofen 400mg tabletlet
6               cetrizine 10mg tablet
7        levocetrizine 5 mg tabletlet
8              metformin 500mg tablet
9              metformin 1g tabletlet
10               amlodipin 5mg tablet
11          amlodipine 10mg tabletlet
12           atorvastatin 10mg tablet
13              atorva 20mg tabletlet
14          azithromycin 250mg tablet
15            azithro 500mg tabletlet
16               losartan 50mg tablet
17    losartan potassium 100mg tablet
18             omeprazol 20mg capsule
19        omeprazole 40mg capsulesule
20           pantoprazole 40mg tablet
21          rabeprazol 20mg tabletlet
22            montelukast 10mg tablet
23          montelukast 5mg tabletlet
24                    dolo 650 tablet
25                crocin 500mg tablet
26          diclofenac 50mg tabletlet
27    diclofenac injectionection 75mg
28         insulin glargine injection
29    regular insulin injectionection
30              salbutamol inhalation
31              budesonide inhalation
32            clopidogrel 75mg tablet
33             aspirin 75mg tabletlet
34               aspirin 150mg tablet
35         telmisartan 40mg tabletlet
36            telmisartan 80mg tablet
37           gliclazid 30mg tabletlet
38             gliclazide 60mg tablet
39          glimepiride 1mg tabletlet
40             glimepiride 2mg tablet
41          glimepiride 4mg tabletlet
42             furosemide 40mg tablet
43      spironolactone 25mg tabletlet
44    hydrochlorothiazide 25mg tablet
45    vitamin d3 60000 iu capsulesule
46              folic acid 5mg tablet
47     calcium carbonate 500mg tablet
48              vit b complex capsule
49                      ifa tabletlet
Name: normalized_name, dtype: object

In [ ]:
master["normalized_name"]

0            paracetamol 500 mg tablet
1            paracetamol 650 mg tablet
2           amoxicillin 250 mg capsule
3           amoxicillin 500 mg capsule
4              ibuprofen 200 mg tablet
5              ibuprofen 400 mg tablet
6              cetirizine 10 mg tablet
7           levocetirizine 5 mg tablet
8              metformin 500 mg tablet
9             metformin 1000 mg tablet
10              amlodipine 5 mg tablet
11             amlodipine 10 mg tablet
12           atorvastatin 10 mg tablet
13           atorvastatin 20 mg tablet
14          azithromycin 250 mg tablet
15          azithromycin 500 mg tablet
16               losartan 50 mg tablet
17              losartan 100 mg tablet
18            omeprazole 20 mg capsule
19            omeprazole 40 mg capsule
20           pantoprazole 40 mg tablet
21            rabeprazole 20 mg tablet
22            montelukast 10 mg tablet
23             montelukast 5 mg tablet
24                  dolo 650 mg tablet
25                crocin 500 mg tablet
26             diclofenac 50 mg tablet
27          diclofenac 75 mg injection
28          insulin glargine injection
29           insulin regular injection
30                  salbutamol inhaler
31                  budesonide inhaler
32            clopidogrel 75 mg tablet
33                aspirin 75 mg tablet
34               aspirin 150 mg tablet
35            telmisartan 40 mg tablet
36            telmisartan 80 mg tablet
37             gliclazide 30 mg tablet
38             gliclazide 60 mg tablet
39             glimepiride 1 mg tablet
40             glimepiride 2 mg tablet
41             glimepiride 4 mg tablet
42             furosemide 40 mg tablet
43         spironolactone 25 mg tablet
44    hydrochlorothiazide 25 mg tablet
45    cholecalciferol 60000 iu capsule
46              folic acid 5 mg tablet
47     calcium carbonate 500 mg tablet
48           vitamin b complex capsule
49              iron folic acid tablet
Name: normalized_name, dtype: object

In [ ]:
master_names = master["normalized_name"].tolist()

## Match Master

##Fuzzy match

In [ ]:
def match_master(medicine):

    match, score, index = process.extractOne(
        medicine,
        master_names,
        scorer=fuzz.token_sort_ratio
    )

    master_id = master.iloc[index]["master_id"]

    return pd.Series([master_id, match, score])

## calling and matching the pharmacy medi name

In [ ]:
pharmacy[["master_id","matched_name","score"]] = pharmacy["normalized_name"].apply(match_master)

In [ ]:
final_inventory = pharmacy[[
    "pharmacy_id",
    "medicine_name",
    "master_id",
    "matched_name",
    "score"
]]

final_inventory = final_inventory.rename(columns={
    "medicine_name":"pharmacy_name"
})

print(final_inventory)

   pharmacy_id                 pharmacy_name master_id  \
0         P001         Paracetamol 500mg Tab      M001
1         P002      Paracetamol 650mg Tablet      M002
2         P003         Amoxycillin 250mg Cap      M003
3         P004    Amoxycillin 500 mg Capsule      M004
4         P005           Ibuprofen 200mg Tab      M005
5         P006        Ibuprofen 400mg Tablet      M006
6         P007            Cetrizine 10mg Tab      M007
7         P008     Levocetrizine 5 mg Tablet      M008
8         P009           Metformin 500mg Tab      M009
9         P010           Metformin 1g Tablet      M010
10        P011             Amlodipin 5mg Tab      M011
11        P012        Amlodipine 10mg Tablet      M012
12        P013         Atorvastatin 10mg Tab      M013
13        P014            Atorva 20mg Tablet      M014
14        P015        Azithromycin 250mg Tab      M015
15        P016          Azithro 500mg Tablet      M016
16        P017             Losartan 50mg Tab      M017
17        P018  Losartan Potassium 100mg Tab      M018
18        P019            Omeprazol 20mg Cap      M019
19        P020       Omeprazole 40mg Capsule      M020
20        P021         Pantoprazole 40mg Tab      M021
21        P022        Rabeprazol 20mg Tablet      M022
22        P023          Montelukast 10mg Tab      M023
23        P024        Montelukast 5mg Tablet      M024
24        P025                  Dolo 650 Tab      M025
25        P026              Crocin 500mg Tab      M026
26        P027        Diclofenac 50mg Tablet      M027
27        P028     Diclofenac Injection 75mg      M028
28        P029          Insulin Glargine Inj      M029
29        P030     Regular Insulin Injection      M030
30        P031         Salbutamol Inhalation      M031
31        P032         Budesonide Inhalation      M032
32        P033          Clopidogrel 75mg Tab      M033
33        P034           Aspirin 75mg Tablet      M034
34        P035             Aspirin 150mg Tab      M035
35        P036       Telmisartan 40mg Tablet      M036
36        P037          Telmisartan 80mg Tab      M037
37        P038         Gliclazid 30mg Tablet      M038
38        P039           Gliclazide 60mg Tab      M039
39        P040        Glimepiride 1mg Tablet      M040
40        P041           Glimepiride 2mg Tab      M041
41        P042        Glimepiride 4mg Tablet      M042
42        P043           Furosemide 40mg Tab      M043
43        P044    Spironolactone 25mg Tablet      M044
44        P045  Hydrochlorothiazide 25mg Tab      M045
45        P046   Vitamin D3 60000 IU Capsule      M049
46        P047            Folic Acid 5mg Tab      M047
47        P048   Calcium Carbonate 500mg Tab      M048
48        P049             Vit B Complex Cap      M049
49        P050                    IFA Tablet      M027

                        matched_name       score
0          paracetamol 500 mg tablet   97.959184
1          paracetamol 650 mg tablet   92.307692
2         amoxicillin 250 mg capsule   86.274510
3         amoxicillin 500 mg capsule   89.285714
4            ibuprofen 200 mg tablet   88.888889
5            ibuprofen 400 mg tablet   83.333333
6            cetirizine 10 mg tablet   86.363636
7         levocetirizine 5 mg tablet   92.592593
8            metformin 500 mg tablet   88.888889
9           metformin 1000 mg tablet   78.260870
10            amlodipine 5 mg tablet   85.714286
11           amlodipine 10 mg tablet   83.333333
12         atorvastatin 10 mg tablet   89.795918
13         atorvastatin 20 mg tablet   69.565217
14        azithromycin 250 mg tablet   90.196078
15        azithromycin 500 mg tablet   73.469388
16             losartan 50 mg tablet   87.804878
17            losartan 100 mg tablet   79.245283
18          omeprazole 20 mg capsule   86.956522
19          omeprazole 40 mg capsule   82.352941
20         pantoprazole 40 mg tablet   97.959184
21          rabeprazole 20 mg tablet   89.795918
22          montelukast 10 mg tablet   97.872340
23           montelukast 5 mg tablet   91.666667
24                dolo 650 mg tablet   90.909091
25              crocin 500 mg tablet   87.179487
26           diclofenac 50 mg tablet   83.333333
27        diclofenac 75 mg injection   80.701754
28        insulin glargine injection  100.000000
29         insulin regular injection   89.285714
30                salbutamol inhaler   82.051282
31                budesonide inhaler   82.051282
32          clopidogrel 75 mg tablet   89.361702
33              aspirin 75 mg tablet   80.952381
34             aspirin 150 mg tablet   87.804878
35          telmisartan 40 mg tablet   92.000000
36          telmisartan 80 mg tablet   97.872340
37           gliclazide 30 mg tablet   80.851064
38           gliclazide 60 mg tablet   88.888889
39           glimepiride 1 mg tablet   83.333333
40           glimepiride 2 mg tablet   88.888889
41           glimepiride 4 mg tablet   83.333333
42           furosemide 40 mg tablet   88.888889
43       spironolactone 25 mg tablet   92.857143
44  hydrochlorothiazide 25 mg tablet   92.063492
45         vitamin b complex capsule   64.285714
46            folic acid 5 mg tablet   88.372093
47   calcium carbonate 500 mg tablet   91.803279
48         vitamin b complex capsule   91.304348
49           diclofenac 50 mg tablet   55.555556

# To Download

In [ ]:
final_inventory.to_csv("pharmacy_inventory.csv", index=False)

## Final Inventory csv file

In [ ]:
from google.colab import files
files.download("pharmacy_inventory.csv")