<a href="https://colab.research.google.com/github/sanjeevchikkam/Medicinemapping/blob/main/MedicineMapping(Sentence%20Transformers).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Start the project

## Install and import libraries

In [1]:
!pip install rapidfuzz
import pandas as pd
import re
from rapidfuzz import process, fuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 15.3 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3

### upload the pharmacy and master medicine id and name

In [2]:
from google.colab import files
uploaded = files.upload()

Saving pharmacy_medicine.csv to pharmacy_medicine.csv
Saving master_medicine.csv to master_medicine.csv

In [3]:
pharmacy = pd.read_csv("pharmacy_medicine.csv")
master = pd.read_csv("master_medicine.csv")

In [4]:
pharmacy["medicine_name"]

0            Paracetamol 500mg Tab
1         Paracetamol 650mg Tablet
2            Amoxycillin 250mg Cap
3       Amoxycillin 500 mg Capsule
4              Ibuprofen 200mg Tab
5           Ibuprofen 400mg Tablet
6               Cetrizine 10mg Tab
7        Levocetrizine 5 mg Tablet
8              Metformin 500mg Tab
9              Metformin 1g Tablet
10               Amlodipin 5mg Tab
11          Amlodipine 10mg Tablet
12           Atorvastatin 10mg Tab
13              Atorva 20mg Tablet
14          Azithromycin 250mg Tab
15            Azithro 500mg Tablet
16               Losartan 50mg Tab
17    Losartan Potassium 100mg Tab
18              Omeprazol 20mg Cap
19         Omeprazole 40mg Capsule
20           Pantoprazole 40mg Tab
21          Rabeprazol 20mg Tablet
22            Montelukast 10mg Tab
23          Montelukast 5mg Tablet
24                    Dolo 650 Tab
25                Crocin 500mg Tab
26          Diclofenac 50mg Tablet
27       Diclofenac Injection 75mg
28            Insulin Glargine Inj
29       Regular Insulin Injection
30           Salbutamol Inhalation
31           Budesonide Inhalation
32            Clopidogrel 75mg Tab
33             Aspirin 75mg Tablet
34               Aspirin 150mg Tab
35         Telmisartan 40mg Tablet
36            Telmisartan 80mg Tab
37           Gliclazid 30mg Tablet
38             Gliclazide 60mg Tab
39          Glimepiride 1mg Tablet
40             Glimepiride 2mg Tab
41          Glimepiride 4mg Tablet
42             Furosemide 40mg Tab
43      Spironolactone 25mg Tablet
44    Hydrochlorothiazide 25mg Tab
45     Vitamin D3 60000 IU Capsule
46              Folic Acid 5mg Tab
47     Calcium Carbonate 500mg Tab
48               Vit B Complex Cap
49                      IFA Tablet
Name: medicine_name, dtype: object

# Write the Normalize text

In [5]:
def normalize_text(text):

    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [6]:
pharmacy["normalized_name"] = pharmacy["medicine_name"].apply(normalize_text)
master["normalized_name"] = master["medicine_name"].apply(normalize_text)

In [7]:
master["normalized_name"]

0            paracetamol 500 mg tablet
1            paracetamol 650 mg tablet
2           amoxicillin 250 mg capsule
3           amoxicillin 500 mg capsule
4              ibuprofen 200 mg tablet
5              ibuprofen 400 mg tablet
6              cetirizine 10 mg tablet
7           levocetirizine 5 mg tablet
8              metformin 500 mg tablet
9             metformin 1000 mg tablet
10              amlodipine 5 mg tablet
11             amlodipine 10 mg tablet
12           atorvastatin 10 mg tablet
13           atorvastatin 20 mg tablet
14          azithromycin 250 mg tablet
15          azithromycin 500 mg tablet
16               losartan 50 mg tablet
17              losartan 100 mg tablet
18            omeprazole 20 mg capsule
19            omeprazole 40 mg capsule
20           pantoprazole 40 mg tablet
21            rabeprazole 20 mg tablet
22            montelukast 10 mg tablet
23             montelukast 5 mg tablet
24                  dolo 650 mg tablet
25                crocin 500 mg tablet
26             diclofenac 50 mg tablet
27          diclofenac 75 mg injection
28          insulin glargine injection
29           insulin regular injection
30                  salbutamol inhaler
31                  budesonide inhaler
32            clopidogrel 75 mg tablet
33                aspirin 75 mg tablet
34               aspirin 150 mg tablet
35            telmisartan 40 mg tablet
36            telmisartan 80 mg tablet
37             gliclazide 30 mg tablet
38             gliclazide 60 mg tablet
39             glimepiride 1 mg tablet
40             glimepiride 2 mg tablet
41             glimepiride 4 mg tablet
42             furosemide 40 mg tablet
43         spironolactone 25 mg tablet
44    hydrochlorothiazide 25 mg tablet
45    cholecalciferol 60000 iu capsule
46              folic acid 5 mg tablet
47     calcium carbonate 500 mg tablet
48           vitamin b complex capsule
49              iron folic acid tablet
Name: normalized_name, dtype: object

In [8]:
pharmacy["normalized_name"]

0            paracetamol 500mg tab
1         paracetamol 650mg tablet
2            amoxycillin 250mg cap
3       amoxycillin 500 mg capsule
4              ibuprofen 200mg tab
5           ibuprofen 400mg tablet
6               cetrizine 10mg tab
7        levocetrizine 5 mg tablet
8              metformin 500mg tab
9              metformin 1g tablet
10               amlodipin 5mg tab
11          amlodipine 10mg tablet
12           atorvastatin 10mg tab
13              atorva 20mg tablet
14          azithromycin 250mg tab
15            azithro 500mg tablet
16               losartan 50mg tab
17    losartan potassium 100mg tab
18              omeprazol 20mg cap
19         omeprazole 40mg capsule
20           pantoprazole 40mg tab
21          rabeprazol 20mg tablet
22            montelukast 10mg tab
23          montelukast 5mg tablet
24                    dolo 650 tab
25                crocin 500mg tab
26          diclofenac 50mg tablet
27       diclofenac injection 75mg
28            insulin glargine inj
29       regular insulin injection
30           salbutamol inhalation
31           budesonide inhalation
32            clopidogrel 75mg tab
33             aspirin 75mg tablet
34               aspirin 150mg tab
35         telmisartan 40mg tablet
36            telmisartan 80mg tab
37           gliclazid 30mg tablet
38             gliclazide 60mg tab
39          glimepiride 1mg tablet
40             glimepiride 2mg tab
41          glimepiride 4mg tablet
42             furosemide 40mg tab
43      spironolactone 25mg tablet
44    hydrochlorothiazide 25mg tab
45     vitamin d3 60000 iu capsule
46              folic acid 5mg tab
47     calcium carbonate 500mg tab
48               vit b complex cap
49                      ifa tablet
Name: normalized_name, dtype: object

### replace tab -> tablet

In [9]:
abbrev = {
    r"\btab\b": "tablet",
    r"\bcap\b": "capsule",
    r"\binj\b": "injection",
    r"\bsyp\b": "syrup"
}

pharmacy["normalized_name"] = pharmacy["normalized_name"].replace(abbrev, regex=True)

In [10]:
abbrev = {
    "tab": "tablet",
    "cap": "capsule",
    "inj": "injection",
    "syp": "syrup"
}

for k, v in abbrev.items():
    pharmacy["normalized_name"] = pharmacy["normalized_name"].str.replace(
        rf"\b{k}\b", v, regex=True
    )

In [11]:
pharmacy["normalized_name"]

0            paracetamol 500mg tablet
1            paracetamol 650mg tablet
2           amoxycillin 250mg capsule
3          amoxycillin 500 mg capsule
4              ibuprofen 200mg tablet
5              ibuprofen 400mg tablet
6               cetrizine 10mg tablet
7           levocetrizine 5 mg tablet
8              metformin 500mg tablet
9                 metformin 1g tablet
10               amlodipin 5mg tablet
11             amlodipine 10mg tablet
12           atorvastatin 10mg tablet
13                 atorva 20mg tablet
14          azithromycin 250mg tablet
15               azithro 500mg tablet
16               losartan 50mg tablet
17    losartan potassium 100mg tablet
18             omeprazol 20mg capsule
19            omeprazole 40mg capsule
20           pantoprazole 40mg tablet
21             rabeprazol 20mg tablet
22            montelukast 10mg tablet
23             montelukast 5mg tablet
24                    dolo 650 tablet
25                crocin 500mg tablet
26             diclofenac 50mg tablet
27          diclofenac injection 75mg
28         insulin glargine injection
29          regular insulin injection
30              salbutamol inhalation
31              budesonide inhalation
32            clopidogrel 75mg tablet
33                aspirin 75mg tablet
34               aspirin 150mg tablet
35            telmisartan 40mg tablet
36            telmisartan 80mg tablet
37              gliclazid 30mg tablet
38             gliclazide 60mg tablet
39             glimepiride 1mg tablet
40             glimepiride 2mg tablet
41             glimepiride 4mg tablet
42             furosemide 40mg tablet
43         spironolactone 25mg tablet
44    hydrochlorothiazide 25mg tablet
45        vitamin d3 60000 iu capsule
46              folic acid 5mg tablet
47     calcium carbonate 500mg tablet
48              vit b complex capsule
49                         ifa tablet
Name: normalized_name, dtype: object

In [12]:
master["normalized_name"]

0            paracetamol 500 mg tablet
1            paracetamol 650 mg tablet
2           amoxicillin 250 mg capsule
3           amoxicillin 500 mg capsule
4              ibuprofen 200 mg tablet
5              ibuprofen 400 mg tablet
6              cetirizine 10 mg tablet
7           levocetirizine 5 mg tablet
8              metformin 500 mg tablet
9             metformin 1000 mg tablet
10              amlodipine 5 mg tablet
11             amlodipine 10 mg tablet
12           atorvastatin 10 mg tablet
13           atorvastatin 20 mg tablet
14          azithromycin 250 mg tablet
15          azithromycin 500 mg tablet
16               losartan 50 mg tablet
17              losartan 100 mg tablet
18            omeprazole 20 mg capsule
19            omeprazole 40 mg capsule
20           pantoprazole 40 mg tablet
21            rabeprazole 20 mg tablet
22            montelukast 10 mg tablet
23             montelukast 5 mg tablet
24                  dolo 650 mg tablet
25                crocin 500 mg tablet
26             diclofenac 50 mg tablet
27          diclofenac 75 mg injection
28          insulin glargine injection
29           insulin regular injection
30                  salbutamol inhaler
31                  budesonide inhaler
32            clopidogrel 75 mg tablet
33                aspirin 75 mg tablet
34               aspirin 150 mg tablet
35            telmisartan 40 mg tablet
36            telmisartan 80 mg tablet
37             gliclazide 30 mg tablet
38             gliclazide 60 mg tablet
39             glimepiride 1 mg tablet
40             glimepiride 2 mg tablet
41             glimepiride 4 mg tablet
42             furosemide 40 mg tablet
43         spironolactone 25 mg tablet
44    hydrochlorothiazide 25 mg tablet
45    cholecalciferol 60000 iu capsule
46              folic acid 5 mg tablet
47     calcium carbonate 500 mg tablet
48           vitamin b complex capsule
49              iron folic acid tablet
Name: normalized_name, dtype: object

In [13]:
master_names = master["normalized_name"].tolist()

## Match Master

#Fuzzy match

In [14]:
def match_master(medicine):

    match, score, index = process.extractOne(
        medicine,
        master_names,
        scorer=fuzz.token_sort_ratio
    )

    master_id = master.iloc[index]["master_id"]

    return pd.Series([master_id, match, score])

## calling and matching the pharmacy medi name

In [15]:
pharmacy[["master_id","matched_name","score"]] = pharmacy["normalized_name"].apply(match_master)

In [16]:
final_inventory = pharmacy[[
    "pharmacy_id",
    "medicine_name",
    "master_id",
    "matched_name",
    "score"
]]

final_inventory = final_inventory.rename(columns={
    "medicine_name":"pharmacy_name"
})

print(final_inventory)

   pharmacy_id                 pharmacy_name master_id  \
0         P001         Paracetamol 500mg Tab      M001
1         P002      Paracetamol 650mg Tablet      M002
2         P003         Amoxycillin 250mg Cap      M003
3         P004    Amoxycillin 500 mg Capsule      M004
4         P005           Ibuprofen 200mg Tab      M005
5         P006        Ibuprofen 400mg Tablet      M006
6         P007            Cetrizine 10mg Tab      M007
7         P008     Levocetrizine 5 mg Tablet      M008
8         P009           Metformin 500mg Tab      M009
9         P010           Metformin 1g Tablet      M010
10        P011             Amlodipin 5mg Tab      M011
11        P012        Amlodipine 10mg Tablet      M012
12        P013         Atorvastatin 10mg Tab      M013
13        P014            Atorva 20mg Tablet      M014
14        P015        Azithromycin 250mg Tab      M015
15        P016          Azithro 500mg Tablet      M016
16        P017             Losartan 50mg Tab      M017
17        P018  Losartan Potassium 100mg Tab      M018
18        P019            Omeprazol 20mg Cap      M019
19        P020       Omeprazole 40mg Capsule      M020
20        P021         Pantoprazole 40mg Tab      M021
21        P022        Rabeprazol 20mg Tablet      M022
22        P023          Montelukast 10mg Tab      M023
23        P024        Montelukast 5mg Tablet      M024
24        P025                  Dolo 650 Tab      M025
25        P026              Crocin 500mg Tab      M026
26        P027        Diclofenac 50mg Tablet      M027
27        P028     Diclofenac Injection 75mg      M028
28        P029          Insulin Glargine Inj      M029
29        P030     Regular Insulin Injection      M030
30        P031         Salbutamol Inhalation      M031
31        P032         Budesonide Inhalation      M032
32        P033          Clopidogrel 75mg Tab      M033
33        P034           Aspirin 75mg Tablet      M034
34        P035             Aspirin 150mg Tab      M035
35        P036       Telmisartan 40mg Tablet      M036
36        P037          Telmisartan 80mg Tab      M037
37        P038         Gliclazid 30mg Tablet      M038
38        P039           Gliclazide 60mg Tab      M039
39        P040        Glimepiride 1mg Tablet      M040
40        P041           Glimepiride 2mg Tab      M041
41        P042        Glimepiride 4mg Tablet      M042
42        P043           Furosemide 40mg Tab      M043
43        P044    Spironolactone 25mg Tablet      M044
44        P045  Hydrochlorothiazide 25mg Tab      M045
45        P046   Vitamin D3 60000 IU Capsule      M049
46        P047            Folic Acid 5mg Tab      M047
47        P048   Calcium Carbonate 500mg Tab      M048
48        P049             Vit B Complex Cap      M049
49        P050                    IFA Tablet      M027

                        matched_name       score
0          paracetamol 500 mg tablet   97.959184
1          paracetamol 650 mg tablet   97.959184
2         amoxicillin 250 mg capsule   86.274510
3         amoxicillin 500 mg capsule   96.153846
4            ibuprofen 200 mg tablet   88.888889
5            ibuprofen 400 mg tablet   88.888889
6            cetirizine 10 mg tablet   86.363636
7         levocetirizine 5 mg tablet   98.039216
8            metformin 500 mg tablet   88.888889
9           metformin 1000 mg tablet   83.720930
10            amlodipine 5 mg tablet   85.714286
11           amlodipine 10 mg tablet   88.888889
12         atorvastatin 10 mg tablet   89.795918
13         atorvastatin 20 mg tablet   74.418605
14        azithromycin 250 mg tablet   90.196078
15        azithromycin 500 mg tablet   78.260870
16             losartan 50 mg tablet   87.804878
17            losartan 100 mg tablet   79.245283
18          omeprazole 20 mg capsule   86.956522
19          omeprazole 40 mg capsule   89.361702
20         pantoprazole 40 mg tablet   97.959184
21          rabeprazole 20 mg tablet   95.652174
22          montelukast 10 mg tablet   97.872340
23           montelukast 5 mg tablet   97.777778
24                dolo 650 mg tablet   90.909091
25              crocin 500 mg tablet   87.179487
26           diclofenac 50 mg tablet   88.888889
27        diclofenac 75 mg injection   90.196078
28        insulin glargine injection  100.000000
29         insulin regular injection  100.000000
30                salbutamol inhaler   82.051282
31                budesonide inhaler   82.051282
32          clopidogrel 75 mg tablet   89.361702
33              aspirin 75 mg tablet   87.179487
34             aspirin 150 mg tablet   87.804878
35          telmisartan 40 mg tablet   97.872340
36          telmisartan 80 mg tablet   97.872340
37           gliclazide 30 mg tablet   86.363636
38           gliclazide 60 mg tablet   88.888889
39           glimepiride 1 mg tablet   88.888889
40           glimepiride 2 mg tablet   88.888889
41           glimepiride 4 mg tablet   88.888889
42           furosemide 40 mg tablet   88.888889
43       spironolactone 25 mg tablet   98.113208
44  hydrochlorothiazide 25 mg tablet   92.063492
45         vitamin b complex capsule   65.384615
46            folic acid 5 mg tablet   88.372093
47   calcium carbonate 500 mg tablet   91.803279
48         vitamin b complex capsule   91.304348
49           diclofenac 50 mg tablet   60.606061

# To Download

In [17]:
final_inventory.to_csv("pharmacy_inventory.csv", index=False)

## Final Inventory csv file

In [18]:
from google.colab import files
files.download("pharmacy_inventory.csv")

In [ ]:
# Sentence Transformer

In [19]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [ ]:
##import senetence transformers and cosine similarity

In [20]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

## Embeddings

In [22]:
pharmacy_embeddings = model.encode(pharmacy["normalized_name"].tolist())
master_embeddings = model.encode(master["normalized_name"].tolist())

In [23]:
similarity_matrix = cosine_similarity(pharmacy_embeddings, master_embeddings)

In [25]:
best_match_index = similarity_matrix.argmax(axis=1)
best_scores = similarity_matrix.max(axis=1)

pharmacy["master_id"] = master.iloc[best_match_index]["master_id"].values
pharmacy["score"] = best_scores

## Result

In [26]:
final_inventory = pharmacy[[
    "pharmacy_id",
    "medicine_name",
    "master_id",
    "score"
]]

final_inventory = final_inventory.rename(columns={
    "medicine_name": "pharmacy_name"
})

In [27]:
final_inventory

   pharmacy_id                 pharmacy_name master_id     score
0         P001         Paracetamol 500mg Tab      M001  0.993024
1         P002      Paracetamol 650mg Tablet      M002  0.992442
2         P003         Amoxycillin 250mg Cap      M003  0.960376
3         P004    Amoxycillin 500 mg Capsule      M004  0.965562
4         P005           Ibuprofen 200mg Tab      M005  0.991051
5         P006        Ibuprofen 400mg Tablet      M006  0.991929
6         P007            Cetrizine 10mg Tab      M007  0.846675
7         P008     Levocetrizine 5 mg Tablet      M008  0.951114
8         P009           Metformin 500mg Tab      M009  0.992130
9         P010           Metformin 1g Tablet      M010  0.883087
10        P011             Amlodipin 5mg Tab      M011  0.865399
11        P012        Amlodipine 10mg Tablet      M012  0.989617
12        P013         Atorvastatin 10mg Tab      M013  0.987872
13        P014            Atorva 20mg Tablet      M014  0.805797
14        P015        Azithromycin 250mg Tab      M015  0.994128
15        P016          Azithro 500mg Tablet      M016  0.896508
16        P017             Losartan 50mg Tab      M017  0.987977
17        P018  Losartan Potassium 100mg Tab      M018  0.913501
18        P019            Omeprazol 20mg Cap      M019  0.979615
19        P020       Omeprazole 40mg Capsule      M020  0.991905
20        P021         Pantoprazole 40mg Tab      M021  0.990863
21        P022        Rabeprazol 20mg Tablet      M022  0.975864
22        P023          Montelukast 10mg Tab      M023  0.985308
23        P024        Montelukast 5mg Tablet      M024  0.984841
24        P025                  Dolo 650 Tab      M025  0.898854
25        P026              Crocin 500mg Tab      M026  0.991958
26        P027        Diclofenac 50mg Tablet      M027  0.989538
27        P028     Diclofenac Injection 75mg      M028  0.984726
28        P029          Insulin Glargine Inj      M029  1.000000
29        P030     Regular Insulin Injection      M030  0.977881
30        P031         Salbutamol Inhalation      M031  0.856299
31        P032         Budesonide Inhalation      M032  0.853346
32        P033          Clopidogrel 75mg Tab      M033  0.991630
33        P034           Aspirin 75mg Tablet      M034  0.990847
34        P035             Aspirin 150mg Tab      M035  0.988411
35        P036       Telmisartan 40mg Tablet      M036  0.987444
36        P037          Telmisartan 80mg Tab      M037  0.984855
37        P038         Gliclazid 30mg Tablet      M038  0.969660
38        P039           Gliclazide 60mg Tab      M039  0.990377
39        P040        Glimepiride 1mg Tablet      M040  0.985975
40        P041           Glimepiride 2mg Tab      M041  0.987942
41        P042        Glimepiride 4mg Tablet      M042  0.988827
42        P043           Furosemide 40mg Tab      M043  0.993642
43        P044    Spironolactone 25mg Tablet      M044  0.993103
44        P045  Hydrochlorothiazide 25mg Tab      M045  0.993155
45        P046   Vitamin D3 60000 IU Capsule      M049  0.570827
46        P047            Folic Acid 5mg Tab      M047  0.993074
47        P048   Calcium Carbonate 500mg Tab      M048  0.993132
48        P049             Vit B Complex Cap      M049  0.799006
49        P050                    IFA Tablet      M037  0.497441

In [28]:
final_inventory.to_csv("pharmacy_inventory.csv", index=False)

##Final inventory csv file

In [29]:
from google.colab import files
files.download("pharmacy_inventory.csv")